"""Competitor-scope behavior with controlled Provider responses.

These tests verify state transitions and the actual synthesis input, not the
semantic quality of positioning generated by a real model.
"""
from __future__ import annotations

from contextlib import redirect_stdout
from copy import deepcopy
import hashlib
import io
import json
from pathlib import Path
import sys
import tempfile
import unittest
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from scripts.tests_v411.test_workflow_v411 import CONTROLLER as C, page, state
from scripts.tests_v411.positioning_provider_samples import BRAND, core_output, market_map


RESEARCH_ACTION = "positioning_market_research"
SYNTHESIS_ACTION = "positioning_value_synthesis"
BRAND_CATEGORY = "持续服务商"
MARKET_PATH = "research/brand_market/competitive_choice_map.json"
CORE_PATH = "positioning/core_positioning.json"
DRAFT_PATH = "positioning/competitor_selection.json"
TARGET_MARKER = "SELECTED_ON_DEMAND_FACT_7391"
PEER_MARKER = "PEER_DETAIL_MUST_NOT_ENTER_SYNTHESIS_5813"
EXCLUDED_MARKER = "EXCLUDED_DETAIL_MUST_NOT_ENTER_SYNTHESIS_9462"
NEW_MARKER = "NEW_COMPARISON_RESEARCH_2847"


def candidate(name, category, kind, notes, role, url, *, relation=None):
    item = {
        "name": name,
        "category": category,
        "kind": kind,
        "research_notes": notes,
        "source_urls": [url],
        "suggested_role": role,
    }
    if relation is not None:
        item["relation_to_brand"] = relation
    return item


RESEARCH = {
    "research_markdown": (
        "客户需要完成周期性任务，可以委托持续服务商、按次处理或自行处理。"
        f"按次服务资料：{TARGET_MARKER}；同类资料：{PEER_MARKER}；"
        f"未纳入对象资料：{EXCLUDED_MARKER}。本材料不预设排名。"
    ),
    "sources": [],
    "brand_category": BRAND_CATEGORY,
    "competitor_candidates": [
        candidate("按次服务", "按次服务商", "category", TARGET_MARKER,
                  "comparison_target", "https://selected.example/service", relation="different_type"),
        candidate("同类服务乙", BRAND_CATEGORY, "brand", PEER_MARKER,
                  "peer_example", "https://peer.example/service", relation="same_type"),
        candidate("边界外服务丙", "无关服务商", "brand", EXCLUDED_MARKER,
                  "excluded", "https://excluded.example/service", relation="different_type"),
        candidate("自行处理", "内部执行", "alternative", "内部人员自行安排周期性任务。",
                  "comparison_target", "https://internal.example/guide", relation="different_type"),
    ],
}
CORE = {
    "user_choice_value": "为周期性任务提供持续的服务安排。",
    "core_positioning_paragraph": f"{BRAND}面向需要持续支持的客户，提供与任务周期相匹配的服务安排。",
    "advantage_explanation": "与按次委托相比，持续服务减少每次重新约定工作的衔接。",
    "applicability_notes": ["仅对本轮确认的比较对象作出判断。"],
}


class CompetitorSelectionTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix="frontmind-competitor-scope-")
        self.addCleanup(self.temp.cleanup)
        self.base = Path(self.temp.name)
        self.job = self.base / "job"
        material = self.base / "company.md"
        material.write_text(
            f"{BRAND}属于{BRAND_CATEGORY}，为周期性任务提供持续安排。ORIGINAL_SCOPE_MATERIAL",
            encoding="utf-8",
        )
        with mock.patch.object(C, "invoke_external_provider", return_value=False):
            self.command("reference-pack", "create", "--brand", BRAND,
                         "--input", str(material), "--job-dir", str(self.job))
        self.assertEqual(RESEARCH_ACTION, state(self.job)["pending_action"]["action"])

    def command(self, *args):
        arguments = C.parser().parse_args(list(args))
        with redirect_stdout(io.StringIO()):
            return arguments.func(arguments)

    def cont(self, *args, revision=None):
        current_revision = state(self.job)["revision"] if revision is None else revision
        return self.command("continue", "--job-dir", str(self.job),
                            "--revision", str(current_revision), *args)

    def read(self, member):
        return json.loads((self.job / member).read_text(encoding="utf-8"))

    def run_provider(self, *, research=None, core=None, callback=None):
        outputs = {
            RESEARCH_ACTION: RESEARCH if research is None else research,
            SYNTHESIS_ACTION: CORE if core is None else core,
        }
        calls = []

        def provider(request_path, request, job):
            action = request["action"]
            self.assertIn(action, outputs, "No unrelated Provider action should run")
            market_path = job / "inputs/market_research.md"
            calls.append({
                "action": action,
                "prompt": (job / request["prompt_path"]).read_text(encoding="utf-8"),
                "market_input": market_path.read_text(encoding="utf-8") if market_path.exists() else "",
                "scope": deepcopy(state(job).get("decisions", {}).get("comparison_scope")),
            })
            C.atomic_json(job / request["expected_output"], deepcopy(outputs[action]))
            return True

        with mock.patch.object(C, "invoke_external_provider", side_effect=provider), redirect_stdout(io.StringIO()):
            result = callback() if callback else C.drive(self.job)
        self.assertEqual(0, result)
        return calls

    def research_pause(self):
        calls = self.run_provider()
        self.assertEqual([RESEARCH_ACTION], [call["action"] for call in calls])
        self.assertEqual("awaiting_competitor_selection", state(self.job)["status"])
        return calls

    def selection(self, targets=("c001",), peers=("c002",)):
        return {"comparison_targets": list(targets), "peer_examples": list(peers)}

    def confirm_scope(self, selection=None, **provider_kwargs):
        chosen = self.selection() if selection is None else selection
        return self.run_provider(
            callback=lambda: self.cont("--competitor-selection", json.dumps(chosen, ensure_ascii=False),
                                       "--confirm-competitors"),
            **provider_kwargs,
        )

    def names(self, items):
        candidates = {item["id"]: item["name"] for item in self.read(MARKET_PATH)["competitor_candidates"]}
        return [item["name"] if isinstance(item, dict) else candidates[item] for item in items]

    def test_research_stops_before_synthesis_and_controller_assigns_candidate_ids(self):
        self.research_pause()
        current = state(self.job)
        self.assertIsNone(current["pending_action"])
        self.assertTrue(current["current_pause"]["must_stop"])
        self.assertFalse((self.job / CORE_PATH).exists())
        self.assertFalse((self.job / "positioning/core_positioning_directions.json").exists())
        candidates = self.read(MARKET_PATH)["competitor_candidates"]
        self.assertEqual(["c001", "c002", "c003", "c004"], [item["id"] for item in candidates])
        self.assertEqual(BRAND_CATEGORY, self.read(MARKET_PATH)["brand_category"])
        self.assertFalse(self.read(DRAFT_PATH).get("confirmed", False))
        for item in RESEARCH["competitor_candidates"]:
            self.assertIn(item["name"], page(self.job))

    def test_empty_continue_does_not_change_candidate_page_or_call_provider(self):
        self.research_pause()
        before = state(self.job)
        before_page = page(self.job)
        before_draft = self.read(DRAFT_PATH)
        with mock.patch.object(C, "invoke_external_provider") as provider:
            self.assertEqual(0, self.cont())
        provider.assert_not_called()
        self.assertEqual(before, state(self.job))
        self.assertEqual(before_page, page(self.job))
        self.assertEqual(before_draft, self.read(DRAFT_PATH))

    def test_selection_can_be_saved_as_draft_without_implicit_confirmation(self):
        self.research_pause()
        with mock.patch.object(C, "invoke_external_provider") as provider:
            self.cont("--competitor-selection", json.dumps(self.selection(("c002",), ()), ensure_ascii=False))
        provider.assert_not_called()
        self.assertEqual("awaiting_competitor_selection", state(self.job)["status"])
        draft = self.read(DRAFT_PATH)
        self.assertEqual(["同类服务乙"], self.names(draft["comparison_targets"]))
        self.assertEqual([], draft["peer_examples"])
        self.assertFalse(draft.get("confirmed", False))
        self.assertFalse(state(self.job)["decisions"].get("comparison_scope", {}).get("confirmed", False))
        calls = self.run_provider(callback=lambda: self.cont("--confirm-competitors"))
        self.assertEqual([SYNTHESIS_ACTION], [call["action"] for call in calls])
        self.assertEqual("within_type", self.read(CORE_PATH)["comparison_scope"]["mode"])

    def test_selection_file_can_replace_suggested_roles(self):
        self.research_pause()
        selected_file = self.base / "selected.json"
        selected_file.write_text(json.dumps(self.selection(("c003",), ()), ensure_ascii=False), encoding="utf-8")
        calls = self.run_provider(callback=lambda: self.cont(
            "--competitor-selection", str(selected_file), "--confirm-competitors"))
        scope = self.read(CORE_PATH)["comparison_scope"]
        self.assertEqual(["边界外服务丙"], self.names(scope["comparison_targets"]))
        self.assertEqual([], scope["peer_examples"])
        self.assertIn(EXCLUDED_MARKER, calls[-1]["market_input"])
        self.assertNotIn(TARGET_MARKER, calls[-1]["market_input"])

    def test_long_literal_input_survives_filesystem_name_limit(self):
        import errno
        literal = "用户的完整需求与比较对象" * 80
        with mock.patch.object(Path, "exists", side_effect=OSError(errno.ENAMETOOLONG, "File name too long")):
            self.assertEqual(literal, C.file_or_text(literal))

    def test_literal_input_does_not_hide_unrelated_filesystem_errors(self):
        import errno
        with mock.patch.object(Path, "exists", side_effect=PermissionError(errno.EACCES, "denied")):
            with self.assertRaises(PermissionError):
                C.file_or_text("private-input.md")
        material = self.base / "long-brief.md"
        material.write_text("完整文件材料", encoding="utf-8")
        self.assertEqual("完整文件材料", C.file_or_text(str(material)))

    def test_role_reversal_keeps_facts_and_overrides_old_research_suggestion(self):
        research = deepcopy(RESEARCH)
        old_notes = PEER_MARKER + "；曾建议仅作举例，不参与比较。"
        research["competitor_candidates"][1]["research_notes"] = old_notes
        current = state(self.job)
        current["metadata"]["positioning_brief"] = "旧要求：同类服务乙仅作举例。客户仍需周期性支持。"
        C.save_state(self.job, current)
        self.run_provider(research=research)
        calls = self.confirm_scope(self.selection(("c002",), ()))
        scope = self.read(CORE_PATH)["comparison_scope"]
        self.assertEqual("within_type", scope["mode"])
        self.assertEqual([], scope["peer_examples"])
        target = scope["comparison_targets"][0]
        self.assertNotIn("suggested_role", target)
        self.assertEqual(old_notes, target["research_notes"])
        self.assertEqual("peer_example", self.read(MARKET_PATH)["competitor_candidates"][1]["suggested_role"])
        self.assertIn("比较对象：同类服务乙。", calls[0]["prompt"])
        self.assertIn(C.comparison_scope_markdown(calls[0]["scope"]), calls[0]["prompt"])
        self.assertIn("本次确认角色：比较对象", calls[0]["market_input"])
        self.assertIn(old_notes, calls[0]["market_input"])

    def test_confirmed_scope_runs_only_synthesis_and_reaches_final_confirmation(self):
        first = self.research_pause()
        confirmation_revision = state(self.job)["revision"]
        second = self.confirm_scope()
        self.assertEqual([RESEARCH_ACTION, SYNTHESIS_ACTION], [call["action"] for call in first + second])
        self.assertEqual("awaiting_core_positioning_confirmation", state(self.job)["status"])
        self.assertEqual(2, len(list((self.job / "reviews").glob("*.md"))))
        scope = state(self.job)["decisions"]["comparison_scope"]
        self.assertTrue(scope["confirmed"])
        self.assertEqual(confirmation_revision, scope["revision"])
        self.assertEqual("between_types", scope["mode"])
        self.assertTrue(scope["scope_statement"].strip())
        self.assertEqual(["按次服务"], self.names(scope["comparison_targets"]))
        self.assertEqual(["同类服务乙"], self.names(scope["peer_examples"]))
        self.assertEqual(scope, self.read(CORE_PATH)["comparison_scope"])
        self.assertEqual(scope, second[0]["scope"])

    def test_synthesis_market_input_contains_target_facts_but_only_peer_identity(self):
        self.research_pause()
        call = self.confirm_scope()[0]
        actual = call["market_input"]
        self.assertTrue(actual, "Inspect the real synthesis market file, not just Prompt instructions")
        self.assertIn(str((self.job / "inputs/market_research.md").resolve()), call["prompt"])
        self.assertIn("按次服务", actual)
        self.assertIn(TARGET_MARKER, actual)
        self.assertIn("https://selected.example/service", actual)
        self.assertIn("同类服务乙", actual)
        self.assertIn(BRAND_CATEGORY, actual)
        for forbidden in (PEER_MARKER, "https://peer.example/service", EXCLUDED_MARKER, "边界外服务丙"):
            self.assertNotIn(forbidden, actual)
            self.assertNotIn(forbidden, call["prompt"])
        self.assertIn(PEER_MARKER, self.read(MARKET_PATH)["research_markdown"])
        self.assertIn(EXCLUDED_MARKER, self.read(MARKET_PATH)["research_markdown"])

    def test_complete_registered_material_precedes_final_writing_instructions(self):
        self.research_pause()
        call = self.confirm_scope()[0]
        source = Path(C.material_sources(self.job)[0]["local_path"])
        complete_material = source.read_text(encoding="utf-8")
        self.assertIn(complete_material, call["prompt"])
        self.assertLess(call["prompt"].index(complete_material), call["prompt"].rfind(C.public_expression_guidance()))

        unrelated = self.base / "unregistered.md"
        unrelated.write_text("UNREGISTERED_TEXT_MUST_NOT_BE_READ_6842", encoding="utf-8")
        misleading_index = self.base / "misleading-index.md"
        misleading_index.write_text(f"[not a registered material](<{unrelated}>)", encoding="utf-8")
        with mock.patch.object(C, "write_reference_context", return_value=misleading_index):
            background = C.positioning_background(self.job)
        self.assertIn(complete_material, background)
        self.assertNotIn(unrelated.read_text(encoding="utf-8"), background)

    def test_scope_modes_change_with_the_selected_objects(self):
        self.research_pause()
        cases = [
            (self.selection(("c001",), ("c002",)), "between_types"),
            (self.selection(("c002",), ()), "within_type"),
            (self.selection(("c001", "c002"), ()), "mixed"),
            (self.selection(("c004",), ("c002",)), "between_types"),
        ]
        for index, (chosen, expected_mode) in enumerate(cases):
            with self.subTest(mode=expected_mode, targets=chosen["comparison_targets"]):
                if index:
                    self.cont("--return-to-competitors")
                calls = self.confirm_scope(chosen)
                self.assertEqual([SYNTHESIS_ACTION], [call["action"] for call in calls])
                scope = self.read(CORE_PATH)["comparison_scope"]
                self.assertEqual(expected_mode, scope["mode"])
                if "c002" in chosen["comparison_targets"]:
                    self.assertIn(PEER_MARKER, calls[0]["market_input"])
                else:
                    self.assertNotIn(PEER_MARKER, calls[0]["market_input"])

    def test_same_type_relation_overrides_category_wording_difference(self):
        aliased = deepcopy(RESEARCH)
        aliased["competitor_candidates"][1]["category"] = "长期支持机构"
        aliased["competitor_candidates"][1]["relation_to_brand"] = "same_type"
        self.assertNotEqual(BRAND_CATEGORY, aliased["competitor_candidates"][1]["category"])
        calls = self.run_provider(research=aliased)
        self.assertEqual([RESEARCH_ACTION], [call["action"] for call in calls])
        calls = self.confirm_scope(self.selection(("c002",), ()))
        self.assertEqual([SYNTHESIS_ACTION], [call["action"] for call in calls])
        scope = self.read(CORE_PATH)["comparison_scope"]
        self.assertEqual("within_type", scope["mode"])
        target = scope["comparison_targets"][0]
        self.assertEqual("长期支持机构", target["category"])
        self.assertEqual("same_type", target["relation_to_brand"])
        self.assertEqual(scope, state(self.job)["decisions"]["comparison_scope"])

    def test_unknown_relation_does_not_infer_between_types_from_category_wording(self):
        uncertain = deepcopy(RESEARCH)
        uncertain["competitor_candidates"][0]["relation_to_brand"] = "unknown"
        self.assertNotEqual(BRAND_CATEGORY, uncertain["competitor_candidates"][0]["category"])
        calls = self.run_provider(research=uncertain)
        self.assertEqual([RESEARCH_ACTION], [call["action"] for call in calls])
        calls = self.confirm_scope(self.selection(("c001",), ()))
        self.assertEqual([SYNTHESIS_ACTION], [call["action"] for call in calls])
        scope = self.read(CORE_PATH)["comparison_scope"]
        self.assertEqual("unspecified", scope["mode"])
        self.assertEqual("unknown", scope["comparison_targets"][0]["relation_to_brand"])
        self.assertTrue(scope["confirmed"])
        self.assertEqual("awaiting_core_positioning_confirmation", state(self.job)["status"])

    def test_known_candidate_object_does_not_force_research_again(self):
        self.research_pause()
        known = {key: RESEARCH["competitor_candidates"][0][key] for key in ("name", "category", "kind")}
        calls = self.confirm_scope(self.selection((known,), ()))
        self.assertEqual([SYNTHESIS_ACTION], [call["action"] for call in calls])
        self.assertIn(TARGET_MARKER, calls[0]["market_input"])

    def test_provider_cannot_replace_controller_owned_confirmed_scope(self):
        self.research_pause()
        forged = {
            "comparison_targets": [{"name": "模型擅自加入对象", "category": "未知", "kind": "brand"}],
            "peer_examples": [], "mode": "within_type", "scope_statement": "模型覆盖确认范围",
            "confirmed": False, "revision": 9999,
        }
        calls = self.confirm_scope(core={**CORE, "comparison_scope": forged})
        stored = self.read(CORE_PATH)["comparison_scope"]
        self.assertEqual(calls[0]["scope"], stored)
        self.assertEqual(stored, state(self.job)["decisions"]["comparison_scope"])
        self.assertNotEqual(forged, stored)
        self.assertNotIn("模型擅自加入对象", page(self.job))

    def test_return_to_candidates_invalidates_working_core_but_not_exported_pack(self):
        self.research_pause()
        self.confirm_scope()
        self.cont("--confirm-core-positioning")
        self.assertEqual("positioning_ready", state(self.job)["status"])
        saved_path = self.job / "deliverables/Reference_Pack_v1/strategy/core_positioning.json"
        immutable_core = saved_path.read_bytes()
        self.assertIn("core_positioning_confirmation", state(self.job)["decisions"])
        with mock.patch.object(C, "invoke_external_provider") as provider:
            self.cont("--return-to-competitors")
        provider.assert_not_called()
        self.assertEqual("awaiting_competitor_selection", state(self.job)["status"])
        self.assertNotIn("core_positioning_confirmation", state(self.job)["decisions"])
        self.assertFalse((self.job / "decisions/core_positioning_confirmation.json").exists())
        self.assertFalse((self.job / CORE_PATH).exists())
        self.assertFalse(self.read(DRAFT_PATH).get("confirmed", False))
        self.assertFalse(state(self.job)["decisions"].get("comparison_scope", {}).get("confirmed", False))
        self.assertEqual(immutable_core, saved_path.read_bytes())
        self.confirm_scope(self.selection(("c002",), ()))
        self.assertEqual("within_type", self.read(CORE_PATH)["comparison_scope"]["mode"])
        self.assertNotIn("core_positioning_confirmation", state(self.job)["decisions"])

    def test_two_ready_returns_export_v2_then_v3_without_modifying_prior_packs(self):
        self.research_pause()
        self.confirm_scope()
        self.cont("--confirm-core-positioning")
        first_delivery = deepcopy(state(self.job)["metadata"]["reference_pack_delivery"])
        first_pack = Path(first_delivery["pack_path"])
        first_zip = Path(first_delivery["portable_zip_path"])

        def snapshot(directory):
            return {str(path.relative_to(directory)): hashlib.sha256(path.read_bytes()).hexdigest()
                    for path in directory.rglob("*") if path.is_file()}

        original_files = snapshot(first_pack)
        original_zip_digest = hashlib.sha256(first_zip.read_bytes()).hexdigest()
        first_core = json.loads((first_pack / "strategy/core_positioning.json").read_text(encoding="utf-8"))
        self.assertEqual(1, first_delivery["pack_version"])
        self.assertEqual("between_types", first_core["comparison_scope"]["mode"])

        self.cont("--return-to-competitors")
        revised = {**CORE, "core_positioning_paragraph": f"{BRAND}的新比较范围使用这一版说明。V2_SCOPE_VALUE_8036"}
        self.confirm_scope(self.selection(("c002",), ()), core=revised)
        second_core = self.read(CORE_PATH)
        self.assertEqual("within_type", second_core["comparison_scope"]["mode"])
        self.assertGreater(second_core["comparison_scope"]["revision"], first_core["comparison_scope"]["revision"])
        self.cont("--confirm-core-positioning")

        self.assertEqual("positioning_ready", state(self.job)["status"])
        second_delivery = state(self.job)["metadata"]["reference_pack_delivery"]
        second_pack = Path(second_delivery["pack_path"])
        second_zip = Path(second_delivery["portable_zip_path"])
        self.assertEqual(2, second_delivery["pack_version"])
        self.assertEqual(first_delivery["pack_id"], second_delivery["pack_id"])
        self.assertNotEqual(first_pack, second_pack)
        self.assertNotEqual(first_zip, second_zip)
        self.assertTrue(second_zip.is_file())
        self.assertEqual(second_core, json.loads((second_pack / "strategy/core_positioning.json").read_text(encoding="utf-8")))
        self.assertEqual(["同类服务乙"], self.names(second_core["comparison_scope"]["comparison_targets"]))
        self.assertEqual([], second_core["comparison_scope"]["peer_examples"])
        self.assertEqual(original_files, snapshot(first_pack))
        self.assertEqual(original_zip_digest, hashlib.sha256(first_zip.read_bytes()).hexdigest())

        second_files = snapshot(second_pack)
        second_zip_digest = hashlib.sha256(second_zip.read_bytes()).hexdigest()
        self.cont("--return-to-competitors")
        third_value = {**CORE, "core_positioning_paragraph": f"{BRAND}同时比较不同类型及同类服务。V3_SCOPE_VALUE_5804"}
        self.confirm_scope(self.selection(("c001", "c002"), ()), core=third_value)
        third_core = self.read(CORE_PATH)
        self.assertEqual("mixed", third_core["comparison_scope"]["mode"])
        self.cont("--confirm-core-positioning")
        third_delivery = state(self.job)["metadata"]["reference_pack_delivery"]
        self.assertEqual(3, third_delivery["pack_version"])
        self.assertEqual(first_delivery["pack_id"], third_delivery["pack_id"])
        third_pack = Path(third_delivery["pack_path"])
        self.assertNotIn(third_pack, (first_pack, second_pack))
        self.assertEqual(third_core, json.loads((third_pack / "strategy/core_positioning.json").read_text(encoding="utf-8")))
        self.assertEqual(original_files, snapshot(first_pack))
        self.assertEqual(second_files, snapshot(second_pack))
        self.assertEqual(original_zip_digest, hashlib.sha256(first_zip.read_bytes()).hexdigest())
        self.assertEqual(second_zip_digest, hashlib.sha256(second_zip.read_bytes()).hexdigest())

    def test_refresh_exports_from_imported_version_then_advances_after_ready_return(self):
        self.research_pause()
        self.confirm_scope()
        self.cont("--confirm-core-positioning")
        self.cont("--return-to-competitors")
        self.confirm_scope(self.selection(("c002",), ()))
        self.cont("--confirm-core-positioning")
        imported_delivery = deepcopy(state(self.job)["metadata"]["reference_pack_delivery"])
        self.assertEqual(2, imported_delivery["pack_version"])
        imported_pack = Path(imported_delivery["pack_path"])
        imported_zip = Path(imported_delivery["portable_zip_path"])
        imported_zip_digest = hashlib.sha256(imported_zip.read_bytes()).hexdigest()
        imported_core = (imported_pack / "strategy/core_positioning.json").read_bytes()
        self.job = self.base / "refresh-v2-job"
        calls = self.run_provider(callback=lambda: self.command(
            "reference-pack", "refresh-market", "--pack", str(imported_zip), "--job-dir", str(self.job)))
        self.assertEqual([RESEARCH_ACTION], [call["action"] for call in calls])
        self.assertEqual("awaiting_competitor_selection", state(self.job)["status"])
        self.confirm_scope(self.selection(("c001",), ("c002",)))
        self.cont("--confirm-core-positioning")
        refreshed = deepcopy(state(self.job)["metadata"]["reference_pack_delivery"])
        self.assertEqual(3, refreshed["pack_version"])
        self.assertEqual(imported_delivery["pack_id"], refreshed["pack_id"])
        refreshed_zip = Path(refreshed["portable_zip_path"])
        refreshed_zip_digest = hashlib.sha256(refreshed_zip.read_bytes()).hexdigest()

        self.cont("--return-to-competitors")
        self.confirm_scope(self.selection(("c002",), ()))
        self.cont("--confirm-core-positioning")
        next_delivery = state(self.job)["metadata"]["reference_pack_delivery"]
        self.assertEqual(4, next_delivery["pack_version"])
        self.assertEqual(imported_delivery["pack_id"], next_delivery["pack_id"])
        self.assertNotEqual(refreshed["pack_path"], next_delivery["pack_path"])
        self.assertEqual(imported_core, (imported_pack / "strategy/core_positioning.json").read_bytes())
        self.assertEqual(imported_zip_digest, hashlib.sha256(imported_zip.read_bytes()).hexdigest())
        self.assertEqual(refreshed_zip_digest, hashlib.sha256(refreshed_zip.read_bytes()).hexdigest())

    def test_refresh_loads_saved_scope_as_unconfirmed_draft_instead_of_suggestions(self):
        self.research_pause()
        self.confirm_scope(self.selection(("c002",), ()))
        self.cont("--confirm-core-positioning")
        delivery = deepcopy(state(self.job)["metadata"]["reference_pack_delivery"])
        self.job = self.base / "refresh-scope-job"
        calls = self.run_provider(callback=lambda: self.command(
            "reference-pack", "refresh-market", "--pack", delivery["portable_zip_path"], "--job-dir", str(self.job)))
        self.assertEqual([RESEARCH_ACTION], [call["action"] for call in calls])
        self.assertEqual("awaiting_competitor_selection", state(self.job)["status"])
        draft = self.read(DRAFT_PATH)
        self.assertEqual(["同类服务乙"], self.names(draft["comparison_targets"]))
        self.assertEqual([], draft["peer_examples"])
        self.assertFalse(draft.get("confirmed", False))
        self.assertFalse(state(self.job)["decisions"].get("comparison_scope", {}).get("confirmed", False))
        self.assertNotIn("core_positioning_confirmation", state(self.job)["decisions"])
        self.assertFalse((self.job / CORE_PATH).exists())
        before = state(self.job)
        with mock.patch.object(C, "invoke_external_provider") as provider:
            self.cont()
        provider.assert_not_called()
        self.assertEqual(before, state(self.job))
        calls = self.run_provider(callback=lambda: self.cont("--confirm-competitors"))
        self.assertEqual([SYNTHESIS_ACTION], [call["action"] for call in calls])
        self.assertEqual("within_type", self.read(CORE_PATH)["comparison_scope"]["mode"])

    def test_reresearch_new_c001_cannot_be_shadowed_by_old_selected_c001(self):
        self.research_pause()
        self.confirm_scope()
        newer = deepcopy(RESEARCH)
        new_marker = "NEW_C001_IDENTITY_9583"
        newer["competitor_candidates"][0] = candidate(
            "新增任务服务戊", "灵活任务服务商", "category", new_marker,
            "comparison_target", "https://replacement.example/service")
        newer["research_markdown"] = "本轮出现新的任务服务类别；旧的按次服务对象不在新候选列表中。"
        calls = self.run_provider(research=newer, callback=lambda: self.cont("--rerun-positioning-research"))
        self.assertEqual([RESEARCH_ACTION], [call["action"] for call in calls])
        self.assertEqual("awaiting_competitor_selection", state(self.job)["status"])
        market = self.read(MARKET_PATH)
        new_candidate = next(item for item in market["competitor_candidates"] if item["name"] == "新增任务服务戊")
        draft = self.read(DRAFT_PATH)
        self.assertIn("按次服务", self.names(draft["comparison_targets"]))
        ids = {}
        for item in market["competitor_candidates"] + draft["comparison_targets"] + draft["peer_examples"]:
            identity = (item["name"], item["category"], item["kind"])
            self.assertEqual(identity, ids.setdefault(item["id"], identity),
                             "A visible candidate ID must not identify both an old and a new object")
        calls = self.confirm_scope(self.selection((new_candidate["id"],), ("c002",)))
        self.assertEqual([SYNTHESIS_ACTION], [call["action"] for call in calls])
        self.assertEqual(["新增任务服务戊"], self.names(self.read(CORE_PATH)["comparison_scope"]["comparison_targets"]))
        self.assertIn(new_marker, calls[0]["market_input"])
        self.assertNotIn(TARGET_MARKER, calls[0]["market_input"])

    def test_duplicate_objects_and_conflicting_roles_are_rejected_without_mutation(self):
        self.research_pause()
        known = {key: RESEARCH["competitor_candidates"][1][key] for key in ("name", "category", "kind")}
        invalid_selections = [
            self.selection(("c001", "c001"), ()),
            self.selection(("c002",), ("c002",)),
            self.selection(("c002",), (known,)),
        ]
        before = state(self.job)
        draft = self.read(DRAFT_PATH)
        for chosen in invalid_selections:
            with self.subTest(selection=chosen), mock.patch.object(C, "invoke_external_provider") as provider:
                with self.assertRaises(C.WorkflowError):
                    self.cont("--competitor-selection", json.dumps(chosen, ensure_ascii=False), "--confirm-competitors")
                provider.assert_not_called()
                self.assertEqual(before, state(self.job))
                self.assertEqual(draft, self.read(DRAFT_PATH))
                self.assertFalse((self.job / CORE_PATH).exists())

    def test_empty_draft_is_allowed_but_empty_or_peer_only_scope_cannot_be_confirmed(self):
        self.research_pause()
        with mock.patch.object(C, "invoke_external_provider") as provider:
            self.cont("--competitor-selection", json.dumps(self.selection((), ())))
        provider.assert_not_called()
        self.assertEqual([], self.read(DRAFT_PATH)["comparison_targets"])
        self.assertEqual([], self.read(DRAFT_PATH)["peer_examples"])
        self.assertEqual("awaiting_competitor_selection", state(self.job)["status"])
        before = state(self.job)
        draft = self.read(DRAFT_PATH)
        for flags in (("--confirm-competitors",),
                      ("--competitor-selection", json.dumps(self.selection((), ("c002",))), "--confirm-competitors")):
            with self.subTest(flags=flags), mock.patch.object(C, "invoke_external_provider") as provider:
                with self.assertRaises(C.WorkflowError):
                    self.cont(*flags)
                provider.assert_not_called()
                self.assertEqual(before, state(self.job))
                self.assertEqual(draft, self.read(DRAFT_PATH))
                self.assertFalse((self.job / CORE_PATH).exists())

    def test_stale_revision_rejects_selection_and_confirmation_without_mutation(self):
        self.research_pause()
        stale_revision = state(self.job)["revision"] - 1
        before = state(self.job)
        draft = self.read(DRAFT_PATH)
        for flags in (("--competitor-selection", json.dumps(self.selection(("c002",), ()))),
                      ("--confirm-competitors",)):
            with self.subTest(flags=flags), mock.patch.object(C, "invoke_external_provider") as provider:
                with self.assertRaises(C.WorkflowError):
                    self.cont(*flags, revision=stale_revision)
                provider.assert_not_called()
                self.assertEqual(before, state(self.job))
                self.assertEqual(draft, self.read(DRAFT_PATH))

    def test_unknown_object_is_researched_then_synthesized_without_another_scope_pause(self):
        self.research_pause()
        custom = {"name": "用户新填平台", "category": "自助平台", "kind": "alternative"}
        supplemented = deepcopy(RESEARCH)
        supplemented["competitor_candidates"] = deepcopy(RESEARCH["competitor_candidates"][:2])
        supplemented["competitor_candidates"][1]["research_notes"] = "属于持续服务商，本轮仅作同类举例。"
        supplemented["competitor_candidates"].append(candidate(
            custom["name"], custom["category"], custom["kind"], NEW_MARKER,
            "comparison_target", "https://new.example/service"))
        # A confirmed-scope research response covers the brand and selected
        # targets; the broad initial market fixture remains unchanged above.
        supplemented["research_markdown"] = (
            f"{BRAND}提供周期性任务的持续服务安排。已选按次服务资料：{TARGET_MARKER}；"
            f"本轮新增的用户新填平台资料：{NEW_MARKER}。同类服务乙仅作为持续服务商的同类举例。"
        )
        reviews_before = len(list((self.job / "reviews").glob("*.md")))
        calls = self.confirm_scope(self.selection(("c001", custom), ("c002",)), research=supplemented)
        self.assertEqual([RESEARCH_ACTION, SYNTHESIS_ACTION], [call["action"] for call in calls])
        self.assertIn(custom["name"], calls[0]["prompt"])
        self.assertIn(NEW_MARKER, calls[1]["market_input"])
        self.assertIn(TARGET_MARKER, calls[1]["market_input"])
        self.assertNotIn(PEER_MARKER, calls[1]["market_input"])
        self.assertEqual("awaiting_core_positioning_confirmation", state(self.job)["status"])
        self.assertEqual(reviews_before + 1, len(list((self.job / "reviews").glob("*.md"))))
        scope = self.read(CORE_PATH)["comparison_scope"]
        self.assertTrue(scope["confirmed"])
        self.assertEqual(["按次服务", custom["name"]], self.names(scope["comparison_targets"]))

    def test_research_can_correct_named_object_kind_without_research_or_pause_loop(self):
        self.research_pause()
        custom = {"name": "用户所说的协作平台", "category": "协作服务", "kind": "brand"}
        corrected_notes = "CORRECTED_KIND_RESEARCH_3792"
        researched = deepcopy(RESEARCH)
        researched["competitor_candidates"].append(candidate(
            custom["name"], "自助协作平台", "alternative", corrected_notes,
            "comparison_target", "https://corrected.example/service", relation="different_type"))
        researched["research_markdown"] = "补查后确认，用户提到的名称指自助协作方式，不是一个具体品牌。"
        reviews_before = len(list((self.job / "reviews").glob("*.md")))
        calls = self.confirm_scope(self.selection((custom,), ()), research=researched)
        self.assertEqual([RESEARCH_ACTION, SYNTHESIS_ACTION], [call["action"] for call in calls])
        self.assertEqual("awaiting_core_positioning_confirmation", state(self.job)["status"])
        self.assertEqual(reviews_before + 1, len(list((self.job / "reviews").glob("*.md"))))
        scope = self.read(CORE_PATH)["comparison_scope"]
        target = scope["comparison_targets"][0]
        self.assertEqual(custom["name"], target["name"])
        self.assertEqual("alternative", target["kind"])
        self.assertEqual("自助协作平台", target["category"])
        self.assertEqual("between_types", scope["mode"])
        self.assertIn(corrected_notes, calls[1]["market_input"])
        same_name = [item for item in self.read(MARKET_PATH)["competitor_candidates"] if item["name"] == custom["name"]]
        self.assertEqual(1, len(same_name))
        self.assertEqual(target["id"], same_name[0]["id"])
        self.cont("--return-to-competitors")
        calls = self.run_provider(callback=lambda: self.cont("--confirm-competitors"))
        self.assertEqual([SYNTHESIS_ACTION], [call["action"] for call in calls])
        self.assertEqual(target, self.read(CORE_PATH)["comparison_scope"]["comparison_targets"][0])

    def test_new_peer_is_identified_by_research_but_only_identity_reaches_synthesis(self):
        self.research_pause()
        custom = {"name": "用户补充同类丁", "category": BRAND_CATEGORY, "kind": "brand"}
        peer_notes = "NEW_PEER_IDENTIFICATION_ONLY_7194"
        peer_url = "https://new-peer.example/service"
        supplemented = deepcopy(RESEARCH)
        supplemented["competitor_candidates"].append(candidate(
            custom["name"], custom["category"], custom["kind"], peer_notes, "peer_example", peer_url))
        reviews_before = len(list((self.job / "reviews").glob("*.md")))
        calls = self.confirm_scope(self.selection(("c001",), (custom,)), research=supplemented)
        self.assertEqual([RESEARCH_ACTION, SYNTHESIS_ACTION], [call["action"] for call in calls])
        self.assertIn(custom["name"], calls[0]["prompt"])
        actual = calls[1]["market_input"]
        self.assertIn(custom["name"], actual)
        self.assertIn(BRAND_CATEGORY, actual)
        self.assertIn(TARGET_MARKER, actual)
        self.assertNotIn(peer_notes, actual)
        self.assertNotIn(peer_url, actual)
        self.assertEqual("awaiting_core_positioning_confirmation", state(self.job)["status"])
        self.assertEqual(reviews_before + 1, len(list((self.job / "reviews").glob("*.md"))))
        core = self.read(CORE_PATH)
        self.assertEqual("between_types", core["comparison_scope"]["mode"])
        self.assertEqual([custom["name"]], self.names(core["comparison_scope"]["peer_examples"]))
        peer = core["comparison_scope"]["peer_examples"][0]
        self.assertEqual({"id", "name", "category", "kind"}, set(peer))
        self.assertEqual(peer_notes, self.read(DRAFT_PATH)["peer_examples"][0]["research_notes"])

    def test_expression_edit_uses_only_synthesis_and_preserves_confirmed_scope(self):
        self.research_pause()
        self.confirm_scope()
        original_scope = deepcopy(self.read(CORE_PATH)["comparison_scope"])
        changed = {**CORE, "core_positioning_paragraph": f"{BRAND}让周期性服务的安排更清楚。"}
        calls = self.run_provider(core=changed, callback=lambda: self.cont(
            "--core-positioning-edits", "只改表达 EXPRESSION_EDIT_1278"))
        self.assertEqual([SYNTHESIS_ACTION], [call["action"] for call in calls])
        self.assertIn("EXPRESSION_EDIT_1278", calls[0]["prompt"])
        self.assertEqual(original_scope, self.read(CORE_PATH)["comparison_scope"])
        self.assertEqual(changed["core_positioning_paragraph"], self.read(CORE_PATH)["core_positioning_paragraph"])
        self.assertEqual("awaiting_core_positioning_confirmation", state(self.job)["status"])

    def test_supplement_preserves_scope_and_researches_before_synthesis(self):
        self.research_pause()
        self.confirm_scope()
        original_scope = deepcopy(self.read(CORE_PATH)["comparison_scope"])
        calls = self.run_provider(callback=lambda: self.cont(
            "--positioning-supplement", "补充实际服务事实 SUPPLEMENT_SCOPE_4419"))
        self.assertEqual([RESEARCH_ACTION, SYNTHESIS_ACTION], [call["action"] for call in calls])
        for call in calls:
            self.assertIn("SUPPLEMENT_SCOPE_4419", call["prompt"])
        self.assertEqual(original_scope, self.read(CORE_PATH)["comparison_scope"])
        self.assertEqual("awaiting_core_positioning_confirmation", state(self.job)["status"])

    def test_new_brand_fact_only_in_supplemental_research_prose_reaches_synthesis_and_pack(self):
        self.research_pause()
        self.confirm_scope()
        brand_fact = "SCOPED_RESEARCH_BRAND_FACT_6529"
        researched = deepcopy(RESEARCH)
        researched["research_markdown"] = (
            f"本轮补充查得：{BRAND}已调整持续服务安排，新增跨周期协作支持。"
            f"该事实标记为 {brand_fact}，只用于解释目标品牌在已确认范围内的能力。"
        )
        self.assertNotIn(brand_fact, json.dumps(researched["competitor_candidates"], ensure_ascii=False))
        self.assertNotIn(brand_fact, json.dumps(CORE, ensure_ascii=False))
        scope = deepcopy(self.read(CORE_PATH)["comparison_scope"])
        calls = self.run_provider(research=researched, callback=lambda: self.cont(
            "--positioning-supplement", "请核实本品牌最新的持续服务安排。"))
        self.assertEqual([RESEARCH_ACTION, SYNTHESIS_ACTION], [call["action"] for call in calls])
        self.assertNotIn(brand_fact, calls[0]["prompt"])
        self.assertIn(brand_fact, calls[1]["market_input"])
        self.assertIn(TARGET_MARKER, calls[1]["market_input"])
        self.assertNotIn(PEER_MARKER, calls[1]["market_input"])
        self.assertNotIn(EXCLUDED_MARKER, calls[1]["market_input"])
        self.assertEqual(scope, self.read(CORE_PATH)["comparison_scope"])
        self.cont("--confirm-core-positioning")
        exported = Path(state(self.job)["metadata"]["reference_pack_delivery"]["portable_zip_path"])
        market_member = C.BRAND_MARKET_MEMBERS["competitive_choice_map"]
        markdown_member = C.BRAND_MARKET_MEMBERS["competitive_choice_map_markdown"]
        saved_market = C.read_reference_member(exported, market_member).decode("utf-8")
        saved_markdown = C.read_reference_member(exported, markdown_member).decode("utf-8")
        self.assertIn(brand_fact, saved_market)
        self.assertIn(brand_fact, saved_markdown)
        self.assertNotIn(brand_fact, json.dumps(self.read(CORE_PATH), ensure_ascii=False),
                         "The Provider core fixture deliberately does not echo the fact; research must carry it")

    def test_scoped_brand_fact_survives_legal_peer_name_mention_in_same_paragraph(self):
        self.research_pause()
        self.confirm_scope()
        brand_fact = "BRAND_FACT_WITH_LEGAL_PEER_MENTION_1648"
        researched = deepcopy(RESEARCH)
        researched["competitor_candidates"] = deepcopy(RESEARCH["competitor_candidates"][:2])
        researched["competitor_candidates"][1]["research_notes"] = "持续服务商；本次只识别其同类举例角色。"
        researched["research_markdown"] = (
            f"补研确认{BRAND}新增了跨周期交接支持，事实标记 {brand_fact}，"
            "可减少持续委托中的重复沟通；同类服务乙属于持续服务商，"
            "本轮仅作为同类举例，不参与品牌之间的胜负比较。"
        )
        self.assertNotIn(brand_fact, json.dumps(researched["competitor_candidates"], ensure_ascii=False))
        self.assertNotIn(brand_fact, json.dumps(CORE, ensure_ascii=False))
        calls = self.run_provider(research=researched, callback=lambda: self.cont(
            "--positioning-supplement", "核实本品牌跨周期交接安排，同类举例角色不变。"))
        self.assertEqual([RESEARCH_ACTION, SYNTHESIS_ACTION], [call["action"] for call in calls])
        actual = calls[1]["market_input"]
        self.assertIn(researched["research_markdown"], actual)
        self.assertIn(brand_fact, actual)
        self.assertNotIn(PEER_MARKER, actual)
        self.assertNotIn(EXCLUDED_MARKER, actual)
        scope = self.read(CORE_PATH)["comparison_scope"]
        self.assertEqual(["按次服务"], self.names(scope["comparison_targets"]))
        self.assertEqual(["同类服务乙"], self.names(scope["peer_examples"]))
        self.assertEqual("between_types", scope["mode"])
        self.cont("--confirm-core-positioning")
        exported = Path(state(self.job)["metadata"]["reference_pack_delivery"]["portable_zip_path"])
        for member in (C.BRAND_MARKET_MEMBERS["competitive_choice_map"],
                       C.BRAND_MARKET_MEMBERS["competitive_choice_map_markdown"]):
            self.assertIn(brand_fact, C.read_reference_member(exported, member).decode("utf-8"))

    def test_reexploration_returns_to_candidates_instead_of_reusing_confirmation(self):
        self.research_pause()
        self.confirm_scope()
        calls = self.run_provider(callback=lambda: self.cont("--rerun-positioning-research"))
        self.assertEqual([RESEARCH_ACTION], [call["action"] for call in calls])
        self.assertEqual("awaiting_competitor_selection", state(self.job)["status"])
        self.assertFalse(self.read(DRAFT_PATH).get("confirmed", False))
        self.assertFalse(state(self.job)["decisions"].get("comparison_scope", {}).get("confirmed", False))
        self.assertFalse((self.job / CORE_PATH).exists())

    def test_scope_and_prose_survive_author_context_and_pack_export_without_rank(self):
        self.research_pause()
        self.confirm_scope()
        core = self.read(CORE_PATH)
        self.assertNotIn("market_tiers", core)
        self.assertNotIn("brand_placement", core)
        C.atomic_json(self.job / "blueprints/p0_blueprint.json", {
            "kind": "p0", "opening": "从需求展开", "sections": [{"heading": "选择", "task": "解释适配"}],
            "ending": "说明边界",
        })
        for content in (C.natural_author_context(self.job, p0=True), C.selected_competitive_context_markdown(self.job)):
            self.assertIn(core["core_positioning_paragraph"], content)
            self.assertIn(core["advantage_explanation"], content)
            self.assertIn(core["comparison_scope"]["scope_statement"], content)
            self.assertIn("按次服务", content)
            self.assertNotIn(EXCLUDED_MARKER, content)
            self.assertNotIn(PEER_MARKER, content)
        self.cont("--confirm-core-positioning")
        self.assertEqual("positioning_ready", state(self.job)["status"])
        self.assertEqual(core, self.read("deliverables/Reference_Pack_v1/strategy/core_positioning.json"))

    def test_null_candidate_urls_do_not_block_flow_or_hide_other_invalid_types(self):
        researched = deepcopy(RESEARCH)
        known_urls = ["https://selected.example/service", "https://selected.example/terms?lang=zh"]
        researched["competitor_candidates"][0]["source_urls"] = [None, known_urls[0], None, known_urls[1]]
        researched["competitor_candidates"][3]["source_urls"] = [None]
        researched["sources"] = [{"title": "已有企业资料", "url": None, "accessed_at": None, "use": "研究说明"}]
        calls = self.run_provider(research=researched)
        self.assertEqual([RESEARCH_ACTION], [call["action"] for call in calls])
        self.assertEqual("awaiting_competitor_selection", state(self.job)["status"])
        stored = self.read(MARKET_PATH)
        self.assertEqual(known_urls, stored["competitor_candidates"][0]["source_urls"])
        self.assertEqual([], stored["competitor_candidates"][3]["source_urls"])
        self.assertEqual(researched["research_markdown"], stored["research_markdown"])
        self.assertEqual(researched["sources"], stored["sources"])
        for original, normalized in zip(researched["competitor_candidates"], stored["competitor_candidates"]):
            for key in ("name", "category", "kind", "research_notes", "relation_to_brand", "suggested_role"):
                self.assertEqual(original[key], normalized[key])
        calls = self.confirm_scope(self.selection(("c001", "c004"), ()))
        self.assertEqual([SYNTHESIS_ACTION], [call["action"] for call in calls])
        self.assertEqual("awaiting_core_positioning_confirmation", state(self.job)["status"])
        self.assertEqual(2, len(list((self.job / "reviews").glob("*.md"))))
        for url in known_urls:
            self.assertIn(url, calls[0]["market_input"])
        self.assertIn(TARGET_MARKER, calls[0]["market_input"])

        for invalid in (7, False, {"url": known_urls[0]}, [known_urls[0]]):
            with self.subTest(invalid_url=invalid):
                malformed = deepcopy(RESEARCH)
                malformed["competitor_candidates"][0]["source_urls"] = [None, known_urls[0], invalid]
                with self.assertRaises(C.WorkflowError):
                    C.normalize_research_result(malformed, BRAND)
        for invalid_list in (None, known_urls[0], {"url": known_urls[0]}):
            with self.subTest(invalid_source_urls=invalid_list):
                malformed = deepcopy(RESEARCH)
                malformed["competitor_candidates"][0]["source_urls"] = invalid_list
                with self.assertRaises(C.WorkflowError):
                    C.normalize_research_result(malformed, BRAND)

    def test_normalizers_keep_legacy_market_and_core_readable_without_inventing_scope(self):
        lightweight_market = {"research_markdown": "历史研究没有候选列表。", "sources": []}
        normalized_market = C.normalize_research_result(deepcopy(lightweight_market), BRAND)
        self.assertEqual(lightweight_market["research_markdown"], normalized_market["research_markdown"])
        self.assertFalse(normalized_market.get("competitor_candidates"))
        self.assertNotIn("comparison_scope", normalized_market)
        normalized_core = C.normalize_core_result(deepcopy(CORE), BRAND)
        self.assertNotIn("comparison_scope", normalized_core)
        self.assertEqual(CORE["core_positioning_paragraph"], normalized_core["core_positioning_paragraph"])
        historical = core_output()
        self.assertEqual(historical, C.validate_core_positioning(historical, BRAND))
        self.assertEqual(market_map(), C.validate_choice_map(market_map(), BRAND))
        self.assertIn(historical["core_positioning_paragraph"], C.core_positioning_markdown(historical))

    def test_confirmation_has_two_content_sections_and_no_research_attachments(self):
        self.research_pause()
        value = {**CORE, "applicability_notes": ["LEGACY_CONDITION_151"],
                 "supporting_proof": ["ARCHIVED_PROOF_271"],
                 "operating_commitments": ["LEGACY_INVESTMENT_373"]}
        self.confirm_scope(core=value)
        text = page(self.job)
        self.assertEqual(["## 核心定位", "## 与已确认竞品的比较", "## 您可以选择"],
                         [line for line in text.splitlines() if line.startswith("## ")])
        self.assertEqual(1, text.count(value["core_positioning_paragraph"]))
        self.assertEqual(1, text.count(value["advantage_explanation"]))
        for marker in ("LEGACY_CONDITION_151", "ARCHIVED_PROOF_271", "LEGACY_INVESTMENT_373", TARGET_MARKER):
            self.assertNotIn(marker, text)
        pause = state(self.job)["current_pause"]
        self.assertEqual([], pause["full_text_links"])
        self.assertEqual([], pause["source_links"])
        internal = C.positioning_context_markdown(self.read(CORE_PATH))
        for marker in ("LEGACY_CONDITION_151", "ARCHIVED_PROOF_271", "LEGACY_INVESTMENT_373"):
            self.assertIn(marker, internal)

    def test_public_pack_matches_page_while_research_and_scope_remain_available(self):
        self.research_pause()
        self.confirm_scope()
        core = self.read(CORE_PATH)
        public = C.core_positioning_markdown(core)
        self.assertTrue(page(self.job).startswith(public.rstrip()))
        self.cont("--confirm-core-positioning")
        exported = Path(state(self.job)["metadata"]["reference_pack_delivery"]["portable_zip_path"])
        self.assertEqual(public, C.read_reference_member(exported, C.STRATEGY_MEMBERS["core_positioning"]).decode())
        research = C.read_reference_member(exported, C.BRAND_MARKET_MEMBERS["competitive_choice_map"]).decode()
        self.assertIn(TARGET_MARKER, research)
        self.assertIn(EXCLUDED_MARKER, research)
        record = json.loads(C.read_reference_member(exported, C.STRATEGY_MEMBERS["core_positioning_record"]))
        self.assertEqual(core["comparison_scope"], record["comparison_scope"])

    def test_downstream_reads_canonical_json_and_keeps_legacy_conditions_internally(self):
        self.research_pause()
        self.confirm_scope(core={**CORE, "applicability_notes": ["INTERNAL_BOUNDARY_112"]})
        self.cont("--confirm-core-positioning")
        root = self.job / "deliverables/Reference_Pack_v1"
        (root / C.STRATEGY_MEMBERS["core_positioning"]).write_text("STALE_MARKDOWN_SHOULD_NOT_OVERRIDE_JSON")
        current = state(self.job)
        current["reference_pack"]["path"] = str(root)
        C.save_state(self.job, current)
        context = C.brand_content_context(self.job)
        self.assertIn(CORE["core_positioning_paragraph"], context["core_positioning"])
        self.assertIn(CORE["advantage_explanation"], context["core_positioning"])
        self.assertIn("INTERNAL_BOUNDARY_112", context["core_positioning"])
        self.assertNotIn("STALE_MARKDOWN", context["core_positioning"])
        self.assertNotIn(PEER_MARKER, context["core_positioning"])


if __name__ == "__main__":
    unittest.main()
